Add pow and sqrt function, and add tests.
Jaden-Drury/Binary-Calculator pull request #4
Opened 2020-09-10 07:44 UTC by ChunxiangYu

Add pow and sqrt.
Add pow sqrt conversion test.

2020-09-10 16:01 UTC, Crysis73 requested changes

2020-09-10 16:01 UTC, Crysis73 commented on .idea/compiler.xml
> +        <module name="Binary-Calculatoryu3" />
Revert this file, we won't want to change the project name

2020-09-10 16:01 UTC, Crysis73 commented on .idea/misc.xml
> +  <component name="ProjectRootManager" version="2" project-jdk-name="13" project-jdk-type="JavaSDK">
We also won't want to change the jdk. You'll want to download jdk 14

2020-09-10 16:01 UTC, Crysis73 commented on src/main/java/BinaryOperations.java
> +    }
Have this function return an int to be consistent with the rest

2020-09-10 16:01 UTC, Crysis73 commented on src/main/java/BinaryOperations.java
> +    }
Have this function return an int to be consistent with the rest

2020-09-10 16:54 UTC, Jaden-Drury requested changes
I approve under the condition the suggested changes @Crysis73 made are done.

2020-09-11 11:56 UTC, Crysis73 approved these changes
Approved.

2020-09-11 15:08 UTC, merged